# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-02-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmaestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_paso_historico', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(fields=['codigo'], name='fmaestros_o_codigo_c405f4_idx'),
        ),
    ]
