# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-02-16 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmaestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apunte',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmaestros.Obra'),
        ),
        migrations.AddIndex(
            model_name='apunte',
            index=models.Index(fields=['obra'], name='fmaestros_a_obra_id_a461fd_idx'),
        ),
    ]
